# Generated by Django 5.0.4 on 2024-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
            ],
        ),
    ]
